#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions


echo "START mesh generation ....."
echo "-----> Create .foam file for post-processing"
touch tuto.foam
#cd system/
#m4 blockMeshDict.m4 > blockMeshDict
#cd ..
echo "-----> Create background mesh with blockMesh"
blockMesh > log.blockMesh
echo "------> scale down to micron size"
transformPoints -scale "(0.001 0.001 0.001)"
echo -e "-----> Prepare case for automatic mesh refinement"
rm -rf 0 const*/polyMesh/refine*

echo "END mesh generation ....."

echo "START Processing ....."
echo "-----> Copy 0.orig directory to new 0 directory" 
rm -rf 0
cp -R 0.orig 0
echo "-----> set the intial water level"
setFields > log.setFields
echo "-----> Decompose case on 4 cores"
decomposePar -force > log.decomposePar
(echo "-----> Run de solver interFoam on 4 cores on :" && date)
mpirun -np 4 interFoam -parallel > log.interFoam
(echo "-----> End of solver calculation on :" && date)

echo "END Processing ....."
reconstructParMesh > log.MeshReconstruct
reconstructPar > log.Reconstruct
##################################################################################
